exclude: ^src/stopments/static/.+$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/oxc-project/mirrors-oxfmt
    rev: v0.61.0
    hooks:
      - id: oxfmt
        types_or: [json, markdown, yaml]

  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: v1.2.5
    hooks:
      - id: tombi-format

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
