name: Release to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  release:
    name: Release
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write
      attestations: write
    needs:
      - test
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6

      - name: Build packages
        run: uv build

      - run: ls dist

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: dist/*

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
