name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Update static files
        run: uv run embed.py

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update static files"
